spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/campussecuritydb?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver


  # spring boot集成mybatis的方式打印sql
#configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
